export const Categories = [
    {
      id: 1,
      img: "/assets/j9.png",
      type: "Plants",
      category:"Plants",
      title: "Aluminum Plant",
      rating: "/assets/Capture.png",
      price: 45,
    },
    {
      id: 2,
      img: "/assets/j10.png",
      type: "Cactus",
      category:"Cactus",
      title: "Ball Cactus",
      rating: "/assets/Capture.png",
      price: 15,
    },
    {
      id: 3,
      img: "/assets/j1.jpg",
      type: "Plants",
      category:"Plants",
      title: "Boncellensis Secullant",
      rating: "/assets/Capture.png",
      price: 34,
    },
    {
      id: 4,
      img: "/assets/j2.jpg",
      type: "Cactus",
      category:"Cactus",
      title: "Cleistocactus",
      rating: "/assets/Capture.png",
      price: 25,
    },
    {
      id: 5,
      img: "/assets/j3.jpg",
      type: "Plants",
      category:"Plants",
      name: "Green Soil Lotus",
      rating: "/assets/Capture.png",
      price: 45,
    },
    {
      id: 6,
      img: "/assets/j11.png",
      type: "Cactus",
      category:"Cactus",
      title: "Mini Astrophytum",
      rating: "/assets/Capture.png",
      price: 34,
    },
    {
      id: 7,
      img: "/assets/j12.png",
      type: "Cactus",
      category:"Cactus",
      title: "Mini San Pedro Cactus",
      rating: "/assets/Capture.png",
      price: 32,
    },
    {
      id: 8,
      img: "/assets/j4.jpg",
      type: "Plants",
      category:"Plants",
      title: "Money Plant",
      rating: "/assets/Capture.png",
      price: 20,
    },
    {
      id: 9,
      img: "/assets/j5.jpg",
      type: "Cactus",
      category:"Cactus",
      title: "Old Lady Cactus",
      rating: "/assets/Capture.png",
      price: 12,
    },
    {
      id: 10,
      img: "/assets/j6.jpg",
      type: "Plants",
      category:"Plants",
      title: "Piorro Quisquam",
      rating: "/assets/Capture.png",
      price: 32,
    },
    {
      id: 11,
      img: "/assets/j7.jpg",
      type: "Plants",
      category:"Plants",
      title: "Rattle Snake Tail",
      rating: "/assets/Capture.png",
      price: 45,
    },
    {
      id: 12,
      img: "/assets/j8.jpg",
      type: "Cactus",
      category:"Cactus",
      title: "Star Cactus",
      rating: "/assets/Capture.png",
      price: 30,
    },
  ];

export default Categories;